# Generated by Django 5.0.1 on 2024-02-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(blank=True, max_length=50, null=True, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка курса')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='описание курса')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(blank=True, max_length=50, null=True, verbose_name='название урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка урока')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='ссылка на видео')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
